### ISSUE TITLE
Plotly figures are not displayed when using DarkerJupyter

### ISSUE THREAD

**Issue by mathis-han** [iamkentleom/DarkerJupyter#5]
When Darker Jupyter is activated plotly figures are not displayed anymore. I have no problems with matplotlib (see example screenshot).

JupyterDarker activated:
![Screenshot_JupyterDarker_activated](https://user-images.githubusercontent.com/98758033/192298459-aca068bf-b48c-4826-84e2-e99ed2ab417b.png)

JupyterDarker deactivated:
![Screenshot _JupyterDarker_deactivated](https://user-images.githubusercontent.com/98758033/192298462-f36ccfb7-7e50-4a72-a947-a666bc2aec8c.png)

**Comment by iamkentleom** [comment]
Hello @mathis-han!

I just released a new version of DarkerJupyter that particularly solves this issue. You may update your extension and try it out. 

I'll closed this issue now. Thank you very much for pointing out this issue and reaching out. I appreciate it very much.
